/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skrla.view;

import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import skrla.controller.ObradaDjelatnik;
import skrla.controller.ObradaPoslovnaJedinica;
import skrla.controller.ObradaTim;
import skrla.model.Djelatnik;
import skrla.model.PoslovnaJedinica;
import skrla.model.Tim;
import skrla.util.OrganizacijaException;
import skrla.util.ViewUtil;

/**
 *
 * @author skrla
 */
public class DjelatnikFrame extends javax.swing.JFrame {

    private ObradaDjelatnik obradaDjelatnik;

    /**
     * Creates new form DjelatnikFrame
     */
    public DjelatnikFrame() {
        initComponents();
        obradaDjelatnik = new ObradaDjelatnik();
        lstDjelatnik.setCellRenderer(new PrikazDjelatnik());
        ucitajDjelatnike();
        ucitajPoslovneJedinice();
        ucitajTimove();
    }

    private void ucitajPoslovneJedinice() {
        DefaultComboBoxModel<PoslovnaJedinica> ms = new DefaultComboBoxModel<>();
        PoslovnaJedinica poslovnaJedinica = new PoslovnaJedinica();
        poslovnaJedinica.setSifraPoslovneJedinice(0);
        poslovnaJedinica.setNazivPoslovneJedinice("Nije odabrano");
        ms.addElement(poslovnaJedinica);
        new ObradaPoslovnaJedinica().read().forEach(s -> {
            ms.addElement(s);
        });
        cbPoslovnaJedinica.setModel(ms);
    }

    private void ucitajTimove() {
        DefaultComboBoxModel<Tim> ms = new DefaultComboBoxModel<>();
        Tim tim = new Tim();
        tim.setSifraTima(0);
        tim.setNazivTima("Nije odabrano");
        ms.addElement(tim);
        new ObradaTim().read().forEach(s -> {
            ms.addElement(s);
        });
        cbTim.setModel(ms);
    }

    private void ucitajDjelatnike() {
        DefaultListModel<Djelatnik> m = new DefaultListModel<>();
        List<Djelatnik> entiteti;
        entiteti = obradaDjelatnik.read(jTxtDjelatnik.getText().trim());

        Collections.sort(entiteti, new ViewUtil());

        for (Djelatnik s : entiteti) {
            m.addElement(s);
        }
        lstDjelatnik.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnPromjenaDjelatnika = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDjelatnik = new javax.swing.JList<>();
        jBtnTaziDjelatnika = new javax.swing.JButton();
        jTxtDjelatnik = new javax.swing.JTextField();
        btnKreirajDjelatnika = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbTim = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPoslovnaJedinica = new javax.swing.JButton();
        cbPoslovnaJedinica = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnPromjenaDjelatnika.setText("Promjeni podatke o djelatniku");
        jBtnPromjenaDjelatnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPromjenaDjelatnikaActionPerformed(evt);
            }
        });

        lstDjelatnik.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDjelatnikValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDjelatnik);

        jBtnTaziDjelatnika.setText("Traži");
        jBtnTaziDjelatnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTaziDjelatnikaActionPerformed(evt);
            }
        });

        jTxtDjelatnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDjelatnikActionPerformed(evt);
            }
        });

        btnKreirajDjelatnika.setText("Kreiraj djelatnika");
        btnKreirajDjelatnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajDjelatnikaActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši djelatnika");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("Traži djelatnika:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtDjelatnik)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnTaziDjelatnika))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jBtnPromjenaDjelatnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnKreirajDjelatnika)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtDjelatnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnTaziDjelatnika, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPromjenaDjelatnika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajDjelatnika)
                    .addComponent(btnObrisi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Tim djelatnika:");

        jLabel3.setText("Poslovna jedinica djelatnika:");

        btnPoslovnaJedinica.setText("Promjeni poslovnu jedinicu");
        btnPoslovnaJedinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoslovnaJedinicaActionPerformed(evt);
            }
        });

        cbPoslovnaJedinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPoslovnaJedinicaActionPerformed(evt);
            }
        });

        btnTim.setText("Promjeni tim djelatnika");
        btnTim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPoslovnaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnPoslovnaJedinica)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPoslovnaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPoslovnaJedinica)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTim)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDjelatnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDjelatnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDjelatnikActionPerformed

    private void jBtnTaziDjelatnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTaziDjelatnikaActionPerformed
        ucitajDjelatnike();
    }//GEN-LAST:event_jBtnTaziDjelatnikaActionPerformed

    private void jBtnPromjenaDjelatnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPromjenaDjelatnikaActionPerformed
        if (lstDjelatnik.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite stavku");
            return;
        }
        new PromjenaDjelatnikFrame(obradaDjelatnik.getEntitet()).setVisible(true);
    }//GEN-LAST:event_jBtnPromjenaDjelatnikaActionPerformed

    private void btnKreirajDjelatnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajDjelatnikaActionPerformed
        new PromjenaDjelatnikFrame().setVisible(true);
    }//GEN-LAST:event_btnKreirajDjelatnikaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (obradaDjelatnik.getEntitet() == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite stavku");
            return;
        }
        if (JOptionPane.showConfirmDialog(
                getRootPane(),
                "Sigurno obrisati \"" + obradaDjelatnik.getEntitet().toString() + "\"?",
                "Brisanje",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            obradaDjelatnik.getEntitet().setAktivan(false);
            obradaDjelatnik.update();
            ucitajDjelatnike();
        } catch (OrganizacijaException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
        lstDjelatnik.repaint();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void lstDjelatnikValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDjelatnikValueChanged
        if (evt.getValueIsAdjusting() || lstDjelatnik.getSelectedValue() == null) {
            return;
        }
        obradaDjelatnik.setEntitet(lstDjelatnik.getSelectedValue());
        var e = obradaDjelatnik.getEntitet();

        if (e.getTim() == null) {
            cbTim.setSelectedIndex(0);
        } else {
            cbTim.setSelectedItem(e.getTim());
        }
        if (e.getPoslovnaJedinica() == null) {
            cbPoslovnaJedinica.setSelectedIndex(0);
        } else {
            cbPoslovnaJedinica.setSelectedItem(e.getPoslovnaJedinica());
        }
    }//GEN-LAST:event_lstDjelatnikValueChanged

    private void btnPoslovnaJedinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoslovnaJedinicaActionPerformed
        if (obradaDjelatnik.getEntitet() == null || cbPoslovnaJedinica.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite poslovnu jedinicu");
            return;
        }
        obradaDjelatnik.getEntitet().setPoslovnaJedinica((PoslovnaJedinica) cbPoslovnaJedinica.getSelectedItem());
        JOptionPane.showMessageDialog(rootPane, "Poslovna jedinica djelatnika uspiješno promjenjena!");
    }//GEN-LAST:event_btnPoslovnaJedinicaActionPerformed

    private void cbPoslovnaJedinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPoslovnaJedinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPoslovnaJedinicaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        if (obradaDjelatnik.getEntitet() == null || cbTim.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite poslovnu jedinicu");
            return;
        }
        obradaDjelatnik.getEntitet().setTim((Tim) cbTim.getSelectedItem());
        JOptionPane.showMessageDialog(rootPane, "Tim djelatnika uspiješno promjenjen!");
    }//GEN-LAST:event_btnTimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajDjelatnika;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPoslovnaJedinica;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<PoslovnaJedinica> cbPoslovnaJedinica;
    private javax.swing.JComboBox<Tim> cbTim;
    private javax.swing.JButton jBtnPromjenaDjelatnika;
    private javax.swing.JButton jBtnTaziDjelatnika;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtDjelatnik;
    private javax.swing.JList<Djelatnik> lstDjelatnik;
    // End of variables declaration//GEN-END:variables

}
