/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skrla.view;

import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DatasetChangeListener;
import org.jfree.data.general.DatasetGroup;
import org.jfree.data.general.DefaultPieDataset;
import skrla.controller.ObradaTim;
import skrla.model.Posao;
import skrla.model.Tim;
import skrla.util.ViewUtil;

/**
 *
 * @author skrla
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    private SimpleDateFormat df;
    private List<Tim> timovi;

    public Izbornik() {
        initComponents();
        postavke();
    }

    private void postavke() {
        setTitle(ViewUtil.getNaslov("Izbornik"));
        ObradaTim obradaTim = new ObradaTim();
        timovi = obradaTim.read();
        postaviIzgled();
        definirajPie();
    }

    private void definirajPie() {

        DefaultPieDataset dataset = new DefaultPieDataset();

        for (Tim t : timovi) {
            var broj = t.getPosao() == null ? 0 : t.getPosao().size();
            dataset.setValue(t.getNazivTima() + " (" + broj + ")", broj);
        }
        var jFreeChart = ChartFactory.createPieChart("Broj poslova po timu", dataset);

        ChartPanel chartPanel = new ChartPanel(jFreeChart);

        pnlPie.setLayout(new BorderLayout());
        pnlPie.add(chartPanel, BorderLayout.CENTER);
        pnlPie.validate();
    }

    private void postaviIzgled() {
        df = new SimpleDateFormat("dd. MM. yyy. HH:mm:ss");

        Vrijeme v = new Vrijeme();
        v.start();
    }

    private class Vrijeme extends Thread {

        @Override
        public void run() {
            jVrijeme.setText(df.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
            run();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jVrijeme = new javax.swing.JLabel();
        pnlPie = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuPoslovnaJedinica = new javax.swing.JMenuItem();
        jMenuDjelatnik = new javax.swing.JMenuItem();
        jMenuTim = new javax.swing.JMenuItem();
        jMenuPosao = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jVrijeme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        pnlPie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPieMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jMenu1.setText("Organizacija Posla");

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miExit.setText("Izlaz");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Programi");

        jMenuPoslovnaJedinica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, 0));
        jMenuPoslovnaJedinica.setText("Poslovna Jedinica");
        jMenuPoslovnaJedinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPoslovnaJedinicaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPoslovnaJedinica);

        jMenuDjelatnik.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuDjelatnik.setText("Djelatnik");
        jMenuDjelatnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDjelatnikActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuDjelatnik);

        jMenuTim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, 0));
        jMenuTim.setText("Tim");
        jMenuTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTimActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuTim);

        jMenuPosao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        jMenuPosao.setText("Posao");
        jMenuPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPosaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPosao);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jVrijeme, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVrijeme, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void jMenuDjelatnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDjelatnikActionPerformed
        new DjelatnikFrame().setVisible(true);
    }//GEN-LAST:event_jMenuDjelatnikActionPerformed

    private void jMenuPoslovnaJedinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPoslovnaJedinicaActionPerformed
        new PoslovnaJedinicaFrame().setVisible(true);
    }//GEN-LAST:event_jMenuPoslovnaJedinicaActionPerformed

    private void jMenuTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTimActionPerformed
        new TimFrame().setVisible(true);
    }//GEN-LAST:event_jMenuTimActionPerformed

    private void jMenuPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPosaoActionPerformed
        new PosaoFrame().setVisible(true);
    }//GEN-LAST:event_jMenuPosaoActionPerformed

    private void pnlPieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPieMouseClicked

    }//GEN-LAST:event_pnlPieMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDjelatnik;
    private javax.swing.JMenuItem jMenuPosao;
    private javax.swing.JMenuItem jMenuPoslovnaJedinica;
    private javax.swing.JMenuItem jMenuTim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jVrijeme;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JPanel pnlPie1;
    // End of variables declaration//GEN-END:variables

}
