/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skrla.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import skrla.controller.ObradaDjelatnik;
import skrla.controller.ObradaPoslovnaJedinica;
import skrla.controller.ObradaTim;
import skrla.model.Djelatnik;
import skrla.model.PoslovnaJedinica;

/**
 *
 * @author skrla
 */
public class PoslovnaJedinicaFrame extends javax.swing.JFrame {

    private ObradaPoslovnaJedinica obradaPoslovnaJedinica;
    private ObradaDjelatnik obradaDjelatnik;
    /**
     * Creates new form PoslovnaJedinicaFrame
     */
    private ObradaPoslovnaJedinica opj;

    public PoslovnaJedinicaFrame() {
        initComponents();
        obradaPoslovnaJedinica = new ObradaPoslovnaJedinica();
        obradaDjelatnik = new ObradaDjelatnik();
        ucitajPoslovneJedinice();
        ucitajPoslovneJedinice1();
        lstDjelatnik.setCellRenderer(new PrikazDjelatnik());
    }

    private void ucitajPoslovneJedinice() {
        DefaultComboBoxModel<PoslovnaJedinica> ms = new DefaultComboBoxModel<>();
        PoslovnaJedinica poslovnaJedinica = new PoslovnaJedinica();
        poslovnaJedinica.setSifraPoslovneJedinice(Integer.valueOf(0));
        poslovnaJedinica.setNazivPoslovneJedinice("Nije odabrano");
        ms.addElement(poslovnaJedinica); 
        if(jComboPoslovnaJedinica1 != null || jComboPoslovnaJedinica1.getSelectedIndex() != 0) {
           new ObradaPoslovnaJedinica().read().forEach(s -> {
               if(!s.equals(jComboPoslovnaJedinica1.getSelectedItem())) {
                  ms.addElement(s);
               }
           });
        } else {
        new ObradaPoslovnaJedinica().read().forEach(s -> {
            ms.addElement(s);
        });
        }

        jComboPoslovnaJedinica.setModel(ms);
    }
    
    private void ucitajPoslovneJedinice1() {
        DefaultComboBoxModel<PoslovnaJedinica> ms = new DefaultComboBoxModel<>();
        PoslovnaJedinica poslovnaJedinica = new PoslovnaJedinica();
        poslovnaJedinica.setSifraPoslovneJedinice(Integer.valueOf(0));
        poslovnaJedinica.setNazivPoslovneJedinice("Nije odabrano");
        ms.addElement(poslovnaJedinica); 
        if(jComboPoslovnaJedinica != null || jComboPoslovnaJedinica.getSelectedIndex() != 0) {
           new ObradaPoslovnaJedinica().read().forEach(s -> {
               if(!s.equals(jComboPoslovnaJedinica.getSelectedItem())) {
                  ms.addElement(s);
               }
           });
        } else {
        new ObradaPoslovnaJedinica().read().forEach(s -> {
            ms.addElement(s);
        });
        }

        jComboPoslovnaJedinica1.setModel(ms);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboPoslovnaJedinica = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jListDjelatnik = new javax.swing.JScrollPane();
        lstDjelatnik = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jComboPoslovnaJedinica1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jListDjelatnik1 = new javax.swing.JScrollPane();
        lstDjelatnik1 = new javax.swing.JList<>();
        btnPrebaci = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboPoslovnaJedinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPoslovnaJedinicaActionPerformed(evt);
            }
        });

        jLabel1.setText("Poslovna jedinica:");

        jListDjelatnik.setViewportView(lstDjelatnik);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListDjelatnik)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboPoslovnaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboPoslovnaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jListDjelatnik, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboPoslovnaJedinica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPoslovnaJedinica1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Poslovna jedinica:");

        jListDjelatnik1.setViewportView(lstDjelatnik1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListDjelatnik1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboPoslovnaJedinica1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboPoslovnaJedinica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jListDjelatnik1))
        );

        btnPrebaci.setText(">>");
        btnPrebaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrebaciActionPerformed(evt);
            }
        });

        btnDodaj.setText("<<");

        jLabel3.setText("Dodaj djelatnike:");

        jLabel4.setText("Prebaci djelatnike:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrebaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrebaci)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboPoslovnaJedinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPoslovnaJedinicaActionPerformed

    }//GEN-LAST:event_jComboPoslovnaJedinicaActionPerformed

    private void jComboPoslovnaJedinica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPoslovnaJedinica1ActionPerformed

    }//GEN-LAST:event_jComboPoslovnaJedinica1ActionPerformed

    private void btnPrebaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrebaciActionPerformed
        DefaultListModel<Djelatnik> m = (DefaultListModel<Djelatnik>)lstDjelatnik.getModel();
        for(Djelatnik d : lstDjelatnik.getSelectedValuesList()){
            m.removeElement(d);
            for(Djelatnik md : obradaPoslovnaJedinica.getEntitet().getDjelatnici()){
                if(md.getSifraDjelatnika() == d.getSifraDjelatnika()){
                    obradaPoslovnaJedinica.getEntitet().getDjelatnici().remove(md);
                    break;
                }
            }
        }        
        lstDjelatnik.repaint();
    }//GEN-LAST:event_btnPrebaciActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnPrebaci;
    private javax.swing.JComboBox<PoslovnaJedinica> jComboPoslovnaJedinica;
    private javax.swing.JComboBox<PoslovnaJedinica> jComboPoslovnaJedinica1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jListDjelatnik;
    private javax.swing.JScrollPane jListDjelatnik1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JList<Djelatnik> lstDjelatnik;
    private javax.swing.JList<Djelatnik> lstDjelatnik1;
    // End of variables declaration//GEN-END:variables
}
