/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skrla.view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import skrla.controller.ObradaDjelatnik;
import skrla.controller.ObradaTim;
import skrla.model.Djelatnik;
import skrla.model.Tim;
import skrla.util.OrganizacijaException;
import skrla.util.ComparatorOrganizacija;
import skrla.util.ViewUtil;

/**
 *
 * @author skrla
 */
public class PrebacijavanjeDjelatnikaSaTimaFrame extends javax.swing.JFrame {

    ObradaTim obradaTim;
    ObradaDjelatnik obradaDjelatnik;

    /**
     * Creates new form PrebacijavanjeDjelatnikaSaTimaFrame
     */
    public PrebacijavanjeDjelatnikaSaTimaFrame() {
        initComponents();
        ucitajPodatke();
    }

    private void ucitajPodatke() {
        setTitle(ViewUtil.getNaslov("Određivanje tima"));
        obradaTim = new ObradaTim();
        obradaDjelatnik = new ObradaDjelatnik();
        ucitajTim();
        ucitajTim1();
        lstDjelatnik.setCellRenderer(new PrikazDjelatnik());
        ucitajDjelatnikeNaTimu((Tim) cbTim.getSelectedItem());
        ucitajDjelatnikeNaTimu1((Tim) cbTim1.getSelectedItem());
    }

    private void ucitajTim() {
        DefaultComboBoxModel<Tim> tm = new DefaultComboBoxModel<>();
        Tim tim = new Tim();
        tim.setSifraTima(Integer.valueOf(0));
        tim.setNazivTima("Djelatnik bez tima");
        tm.addElement(tim);
        if (cbTim1.getSelectedItem() != null || cbTim1.getSelectedIndex() != 0) {
            new ObradaTim().read().forEach(s -> {
                if (!s.equals(cbTim1.getSelectedItem())) {
                    tm.addElement(s);
                }
            });
        } else {
            new ObradaTim().read().forEach(s -> {
                tm.addElement(s);
            });
        }

        cbTim.setModel(tm);
    }

    private void ucitajTim1() {
        DefaultComboBoxModel<Tim> tm = new DefaultComboBoxModel<>();
        Tim tim = new Tim();
        tim.setSifraTima(Integer.valueOf(0));
        tim.setNazivTima("Djelatnik bez tima");
        tm.addElement(tim);
        if (cbTim.getSelectedItem() != null || cbTim.getSelectedIndex() != 0) {
            new ObradaTim().read().forEach(s -> {
                if (!s.equals(cbTim.getSelectedItem())) {
                    tm.addElement(s);
                }
            });
        } else {
            new ObradaTim().read().forEach(s -> {
                tm.addElement(s);
            });
        }

        cbTim1.setModel(tm);
    }

    private void ucitajDjelatnikeNaTimu(Tim odabran) {
        DefaultListModel<Djelatnik> m = new DefaultListModel<>();
        List<Djelatnik> djelatnici;
        djelatnici = obradaDjelatnik.read();
        Tim tim = odabran;

        if (cbTim.getSelectedIndex() != 0) {
            for (Djelatnik d : djelatnici) {
                if (d.getTim() == null) {
                    continue;
                }
                if (d.getTim().getSifraTima() == odabran.getSifraTima()) {
                    m.addElement(d);
                }
            }
        } else {
            for (Djelatnik d : djelatnici) {
                if (d.getTim() == null) {
                    m.addElement(d);
                }
            }
        }
        lstDjelatnik.setModel(m);
    }

    private void ucitajDjelatnikeNaTimu1(Tim odabran) {
        DefaultListModel<Djelatnik> m = new DefaultListModel<>();
        List<Djelatnik> djelatnici;
        djelatnici = obradaDjelatnik.read();
        Tim tim = odabran;
        if (cbTim1.getSelectedIndex() != 0) {
            for (Djelatnik d : djelatnici) {
                if (d.getTim() == null) {
                    continue;
                }
                if (d.getTim().getSifraTima() == odabran.getSifraTima()) {
                    m.addElement(d);
                }
            }
        } else {
            for (Djelatnik d : djelatnici) {
                if (d.getTim() == null) {
                    m.addElement(d);
                }
            }
        }
        lstDjelatnik1.setModel(m);
    }

    private void spremi() {
        try {
            obradaDjelatnik.update();

        } catch (OrganizacijaException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbTim1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDjelatnik1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbTim = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDjelatnik = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTim1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Odaberite tim na koji želite prebaciti djelatnike:");

        jScrollPane1.setViewportView(lstDjelatnik1);

        jLabel6.setText("Djelatnici na timu:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(cbTim1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        cbTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTimActionPerformed(evt);
            }
        });

        jLabel3.setText("Trenutni tim:");

        lstDjelatnik.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDjelatnikValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstDjelatnik);

        jLabel5.setText("Djelatnici na timu:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Dodaj djelatnike:");

        jLabel1.setText("Prebaci djelatnike:");

        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel<Djelatnik> m = (DefaultListModel<Djelatnik>) lstDjelatnik1.getModel();
        if (cbTim.getSelectedIndex() != 0) {
            obradaTim.setEntitet((Tim) cbTim.getSelectedItem());
            var e = obradaTim.getEntitet();
            for (Djelatnik d : lstDjelatnik1.getSelectedValuesList()) {
                m.removeElement(d);
                d.setTim(e);
                obradaDjelatnik.setEntitet(d);
                spremi();
            }
        } else {
            for (Djelatnik d : lstDjelatnik1.getSelectedValuesList()) {
                m.removeElement(d);
                d.setPoslovnaJedinica(null);
                obradaDjelatnik.setEntitet(d);
                spremi();
            }
        }
        ucitajDjelatnikeNaTimu((Tim) cbTim.getSelectedItem());
        ucitajDjelatnikeNaTimu1((Tim) cbTim1.getSelectedItem());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstDjelatnikValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDjelatnikValueChanged

    }//GEN-LAST:event_lstDjelatnikValueChanged

    private void cbTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTimActionPerformed
        ucitajDjelatnikeNaTimu((Tim) cbTim.getSelectedItem());
    }//GEN-LAST:event_cbTimActionPerformed

    private void cbTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTim1ActionPerformed
        ucitajDjelatnikeNaTimu1((Tim) cbTim1.getSelectedItem());
    }//GEN-LAST:event_cbTim1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel<Djelatnik> m = (DefaultListModel<Djelatnik>) lstDjelatnik.getModel();
        if (cbTim1.getSelectedIndex() != 0) {
            obradaTim.setEntitet((Tim) cbTim1.getSelectedItem());
            var e = obradaTim.getEntitet();
            for (Djelatnik d : lstDjelatnik.getSelectedValuesList()) {
                m.removeElement(d);
                d.setTim(e);
                obradaDjelatnik.setEntitet(d);
                spremi();

            }
        } else {
            for (Djelatnik d : lstDjelatnik.getSelectedValuesList()) {
                m.removeElement(d);
                d.setTim(null);
                obradaDjelatnik.setEntitet(d);
                spremi();
            }
        }
        ucitajDjelatnikeNaTimu((Tim) cbTim.getSelectedItem());
        ucitajDjelatnikeNaTimu1((Tim) cbTim1.getSelectedItem());
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Tim> cbTim;
    private javax.swing.JComboBox<Tim> cbTim1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Djelatnik> lstDjelatnik;
    private javax.swing.JList<Djelatnik> lstDjelatnik1;
    // End of variables declaration//GEN-END:variables
}
