/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skrla.view;

import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import skrla.controller.ObradaDjelatnik;
import skrla.controller.ObradaTim;
import skrla.model.Djelatnik;
import skrla.model.Tim;
import skrla.util.ViewUtil;

/**
 *
 * @author skrla
 */
public class TimFrame extends javax.swing.JFrame {

    private ObradaTim obradaTim;
    private ObradaDjelatnik obradaDjelatnik;
    /**
     * Creates new form TimFrame
     */
    public TimFrame() {
        initComponents();
        obradaTim = new ObradaTim();
        obradaDjelatnik = new ObradaDjelatnik();
        ucitajTim();
    }
    
    private void ucitajTim() {
        DefaultListModel<Tim> m = new DefaultListModel<>();
        List<Tim> entiteti = obradaTim.read();

        for (Tim s : entiteti) {
            m.addElement(s);
        }
        // implementirati ćemo custom renderer https://www.codejava.net/java-se/swing/jlist-custom-renderer-example
        jListTim.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnTrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTim = new javax.swing.JList<>();
        jTxtTim = new javax.swing.JTextField();
        jBtnPromjenaTim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDjelatnik = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnTrazi.setText("Traži");

        jListTim.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTimValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListTim);

        jBtnPromjenaTim.setText("Promjeni podatke tima");
        jBtnPromjenaTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPromjenaTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtTim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnTrazi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnPromjenaTim, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnTrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPromjenaTim)
                .addContainerGap())
        );

        jLabel1.setText("Djelatnici na timu:");

        jScrollPane2.setViewportView(jListDjelatnik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPromjenaTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPromjenaTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPromjenaTimActionPerformed

    private void jListTimValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTimValueChanged
         if (evt.getValueIsAdjusting() || jListTim.getSelectedValue() == null) {
            return;
        }
        obradaTim.setEntitet(jListTim.getSelectedValue());
        var e = obradaTim.getEntitet();
        
        DefaultListModel<Djelatnik> m = new DefaultListModel<>();
        if (e.getDjelatnik()!= null) {
            Collections.sort(e.getDjelatnik(), new ViewUtil());
            m.addAll(e.getDjelatnik());
        }
        jListDjelatnik.setModel(m);
    }//GEN-LAST:event_jListTimValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPromjenaTim;
    private javax.swing.JButton jBtnTrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Djelatnik> jListDjelatnik;
    private javax.swing.JList<Tim> jListTim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtTim;
    // End of variables declaration//GEN-END:variables


}
